### ISSUE TITLE
请问怎么修改Json解析库？你项目默认是GSon的，但是我并不想用Gson

### ISSUE THREAD

**Issue by Alexxiaopang** [wobiancao/sugar#4]

**Comment by Alexxiaopang** [comment]
可以了，我下载你的库直接修改

**Comment by wobiancao** [comment]
谢谢反馈，你说的是网络请求的转换吗，后续计划加上可以选择的转换即可

**Comment by Alexxiaopang** [comment]
对，就是解析数据返回的数据，阿里巴巴的fastjson会好用很多，对于一些空字串或者类型变换会好很多，GSON处理真的太差了

**Comment by wobiancao** [comment]
这个已经加上了，支持使用自己的ConverterFactory
```
 //自定义ConverterFactory
                .addConverterFactory(FastJsonConverterFactory.create())
```
[DemoConfigure](https://github.com/wobiancao/sugar/blob/master/demo/src/main/java/com/sugar/demo/config/DemoConfigure.java)
