### ISSUE TITLE
导入库有点问题

### ISSUE THREAD

**Issue by yyclang** [wobiancao/sugar#7]
按照大神第一种方式导入到工程里，运行报一个异常
No cached version of com.github.glomadrian:loadingballs:1.1 available for offline mode.
大神，能否更新一下你的库的依赖。

**Comment by yyclang** [comment]
另外尝试将你的库包导出来，出现下列情况：
* What went wrong:
Could not resolve all files for configuration ':sugarlibrary:lintClassPath'.
> Could not download lint-gradle.jar (com.android.tools.lint:lint-gradle:26.3.2): No cached version available for offline mode
> Could not download lint.jar (com.android.tools.lint:lint:26.3.2): No cached version available for offline mode
> Could not download lint-checks.jar (com.android.tools.lint:lint-checks:26.3.2): No cached version available for offline mode
> Could not download lint-api.jar (com.android.tools.lint:lint-api:26.3.2): No cached version available for offline mode
> Could not download intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.3.2): No cached version available for offline mode
> Could not download kotlin-compiler.jar (com.android.tools.external.com-intellij:kotlin-compiler:26.3.2): No cached version available for offline mode
> Could not download uast.jar (com.android.tools.external.org-jetbrains:uast:26.3.2): No cached version available for offline mode

**Comment by wobiancao** [comment]
是这个库 https://github.com/glomadrian/loading-balls
它没有更新额
