### ISSUE TITLE
你好，我这边需要商用，可能要改动到代码，是否可以更改？

### ISSUE THREAD

**Issue by Alexxiaopang** [wobiancao/sugar#9]
如题，不会更改你的版权信息，但是代码里面的一些逻辑需要变更一下

**Comment by wobiancao** [comment]
> 如题，不会更改你的版权信息，但是代码里面的一些逻辑需要变更一下

没问题哈

**Comment by Alexxiaopang** [comment]
谢谢，只是用于项目上线，感谢老哥的无私奉献



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "兔子吃过窝边草"<notifications@github.com&gt;; 
发送时间: 2019年12月26日(星期四) 上午10:00
收件人: "wobiancao/sugar"<sugar@noreply.github.com&gt;; 
抄送: "仰望半夜的月"<610611029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wobiancao/sugar] 你好，我这边需要商用，可能要改动到代码，是否可以更改？ (#9)



 
如题，不会更改你的版权信息，但是代码里面的一些逻辑需要变更一下
  
没问题哈
